[package]
name = "sausagewiki"
version = "0.1.0"
authors = ["Magnus Hoff <maghoff@gmail.com>"]
license = "GPL-3.0"

[profile.release]
panic = "abort"

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
hyper = "0.11"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
serde_derive = "1.0.0"
serde = "1.0.0"
serde_urlencoded = "0.5.0"
serde_json = "1.0"
slug = "0.1"
r2d2 = "0.7"
r2d2-diesel = "0.16"
regex = "0.2"
titlecase = "0.10"
lazy_static = "0.2"
chrono = "0.4"
clap = "2.26"
bart = "0.1.4"
bart_derive = "0.1.4"

[dependencies.libsqlite3-sys]
features = ["bundled"]
version = "*"

[dependencies.diesel]
default-features = false
features = ["sqlite", "chrono"]
version = "0.16"

[dependencies.diesel_codegen]
default-features = false
features = ["sqlite"]
version = "0.16"

[dependencies.num]
default-features = false
version = "0.1"

[dependencies.pulldown-cmark]
version = "0.0.11"
default-features = false

[dependencies.static_resource_derive]
path = "libs/static_resource_derive"

[build-dependencies]
quote = "0.3.10"
walkdir = "1"

[build-dependencies.diesel]
default-features = false
features = ["sqlite", "chrono"]
version = "0.16.0"

[workspace]
